markdown: kramdown
pygments: true
safe: false
permalink: /posts/:title.html
exclude:
  - README.md

name: Jun
host: jzq84229.github.io
desc: Jun的代码笔记

custom:
    category:
        default: Default Category
        another: Another Category
    categories:
      - name:  default
        title: Default Category

      - name:  another
        title: Another Category

    scrollingLoadCount: 2                          # 滚屏自动加载文章数量，“0”为关闭

meta:
    author:
        name: Jun
        email: your-email@example.com
        disqus: jzh                                 # Disqus缩略标识
        gcse: 012651674471710951982:gsattlz1pkk     # Google自定义搜索标识ID
        github: jzq84229                            # GitHub账号
        gravatar: 5b7d88240e1e2b9755ac9fca17d5cd8e  # Gravatar头像标识
        ganalytics: UA-66208420-1                   # Google分析ID

    disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
    gravatar: http://en.gravatar.com/avatar/        # Gravatar头像服务器地址
